# Generated by Django 4.2 on 2024-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('board_type', models.CharField(max_length=200)),
                ('win_or_loss', models.CharField(choices=[('WIN', 'win'), ('LOSS', 'loss')], max_length=200)),
                ('score', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
