# Generated by Django 4.2 on 2024-04-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wonders_app', '0003_remove_card_board_card_card_image_instancecards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_wins', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wonders_app.player'),
        ),
    ]
